use super::{bi, BuiltinEffect, BuiltinEmit, BuiltinInfo, ResultHeap, ENS_LIST_APPEND, NO_F};
use crate::ast::{Builtin, BuiltinFamily};

pub(crate) fn info_list(b: Builtin) -> BuiltinInfo {
    use Builtin::*;
    use BuiltinEmit::*;
    use ResultHeap::*;
    let pure = BuiltinEffect::Pure;
    let f = BuiltinFamily::List;
    match b {
        ListLen => bi(
            f,
            1,
            1,
            pure,
            Some("lumia_len"),
            NO_F,
            UnaryObjScalar,
            false,
            Never,
        )
        .with_list_receiver_rt("lumia_list_len"),
        ListGet => bi(
            f,
            2,
            2,
            pure,
            Some("lumia_get"),
            NO_F,
            ObjI64OptionTags,
            false,
            Typed,
        )
        .with_list_receiver_rt("lumia_list_get"),
        ListSlice => bi(
            f,
            2,
            2,
            pure,
            Some("lumia_list_slice"),
            NO_F,
            ObjI64Ptr,
            // Escape only when the slice result escapes (propagate), not every use.
            false,
            Always,
        )
        .with_string_receiver_rt("lumia_str_slice"),
        ListAppend => bi(
            f,
            2,
            2,
            pure,
            Some("lumia_list_append"),
            ENS_LIST_APPEND,
            ObjI64Ptr,
            true,
            Always,
        ),
        ListConcat => bi(
            f,
            2,
            2,
            pure,
            Some("lumia_concat"),
            NO_F,
            ObjObjPtr,
            true,
            Always,
        )
        .with_string_receiver_rt("lumia_str_concat"),
        ListTake => bi(
            f,
            2,
            2,
            pure,
            Some("lumia_list_take"),
            NO_F,
            ObjI64Ptr,
            // Same as ListSlice: copy elem pointers only if result escapes.
            false,
            Always,
        )
        .with_string_receiver_rt("lumia_str_take"),
        ListReverse => bi(
            f,
            1,
            1,
            pure,
            Some("lumia_list_reverse"),
            NO_F,
            UnaryObjPtr,
            true,
            Always,
        )
        .with_string_receiver_rt("lumia_str_reverse"),
        ListSort => bi(
            f,
            1,
            1,
            pure,
            Some("lumia_list_sort"),
            NO_F,
            UnaryObjPtr,
            true,
            Always,
        ),
        ListSortByKeys => bi(
            f,
            2,
            2,
            pure,
            Some("lumia_list_sort_by_keys"),
            NO_F,
            ObjObjPtr,
            true,
            Always,
        ),
        ListParMap => bi(
            f,
            2,
            2,
            pure,
            Some("lumia_list_par_map"),
            NO_F,
            Custom,
            true,
            Always,
        ),
        ListParFold => bi(
            f,
            3,
            3,
            pure,
            Some("lumia_list_par_fold"),
            NO_F,
            Custom,
            true,
            Typed,
        ),
        ListJoin => bi(
            f,
            2,
            2,
            pure,
            Some("lumia_list_join"),
            NO_F,
            ObjObjPtr,
            false,
            Always,
        ),
        Elems => bi(
            f,
            1,
            1,
            pure,
            Some("lumia_elems"),
            NO_F,
            UnaryObjPtr,
            true,
            Always,
        ),
        Range => bi(
            f,
            2,
            2,
            pure,
            Some("lumia_range"),
            NO_F,
            I64I64Ptr,
            true,
            Always,
        ),
        RangeInclusive => bi(
            f,
            2,
            2,
            pure,
            Some("lumia_range_inclusive"),
            NO_F,
            I64I64Ptr,
            true,
            Always,
        ),
        _ => unreachable!("info_list: {b:?}"),
    }
}
