use super::{bi, BuiltinEffect, BuiltinEmit, BuiltinInfo, ResultHeap, NO_F};
use crate::ast::{Builtin, BuiltinFamily};

pub(crate) fn info_task(b: Builtin) -> BuiltinInfo {
    use Builtin::*;
    use BuiltinEmit::*;
    use ResultHeap::*;
    let io = BuiltinEffect::Io;
    let f = BuiltinFamily::Task;
    match b {
        ChannelNew => bi(
            f,
            1,
            1,
            io,
            Some("lumia_channel_new"),
            NO_F,
            Custom,
            true,
            Always,
        ),
        ChannelSend => bi(
            f,
            2,
            2,
            io,
            Some("lumia_channel_send"),
            NO_F,
            Custom,
            true,
            Never,
        ),
        ChannelRecv => bi(
            f,
            1,
            1,
            io,
            Some("lumia_channel_recv"),
            NO_F,
            UnaryObjScalar,
            false,
            Typed,
        ),
        ChannelRecvOpt => bi(f, 1, 1, io, Some("lumia_channel_recv_opt"), NO_F, Custom, false, Always),
        ChannelClose => bi(
            f,
            1,
            1,
            io,
            Some("lumia_channel_close"),
            NO_F,
            Custom,
            false,
            Never,
        ),
        TaskJoin => bi(
            f,
            1,
            1,
            io,
            Some("lumia_task_join"),
            NO_F,
            UnaryObjScalar,
            false,
            Typed,
        ),
        TaskJoinOpt => bi(
            f,
            1,
            1,
            io,
            Some("lumia_task_join_opt"),
            NO_F,
            Custom,
            false,
            Always,
        ),
        TaskSpawn => bi(f, 1, 1, io, Some("lumia_task_spawn"), NO_F, Custom, true, Always),
        ScopeEnter => bi(
            f,
            1,
            1,
            io,
            Some("lumia_scope_enter"),
            NO_F,
            Custom,
            false,
            Never,
        ),
        ScopeLeave => bi(
            f,
            0,
            0,
            io,
            Some("lumia_scope_leave"),
            NO_F,
            NullaryVoid,
            false,
            Never,
        ),
        ScopeCancel => bi(
            f,
            0,
            0,
            io,
            Some("lumia_scope_cancel"),
            NO_F,
            NullaryVoid,
            false,
            Never,
        ),
        _ => unreachable!("info_task: {b:?}"),
    }
}
