use super::{bi, BuiltinEffect, BuiltinEmit, BuiltinInfo, ResultHeap, ENS_LIST_APPEND, NO_F};
use crate::ast::{Builtin, BuiltinFamily};

pub(crate) fn info_list(b: Builtin) -> BuiltinInfo {
    use Builtin::*;
    use BuiltinEmit::*;
    use ResultHeap::*;
    let pure = BuiltinEffect::Pure;
    let f = BuiltinFamily::List;
    match b {
        ListLen => bi(
            f,
            1,
            1,
            pure,
            Some("lumi_len"),
            NO_F,
            UnaryObjScalar,
            false,
            Never,
        ),
        ListGet => bi(
            f,
            2,
            2,
            pure,
            Some("lumi_get"),
            NO_F,
            ObjI64OptionTags,
            false,
            Typed,
        ),
        ListSlice => bi(
            f,
            2,
            2,
            pure,
            Some("lumi_list_slice"),
            NO_F,
            ObjI64Ptr,
            // Not may_capture: seed must not force the source when the view is
            // local-only. Propagate marks the parent if the slice result escapes.
            false,
            Always,
        ),
        ListAppend => bi(
            f,
            2,
            2,
            pure,
            Some("lumi_list_append"),
            ENS_LIST_APPEND,
            ObjI64Ptr,
            true,
            Always,
        ),
        ListConcat => bi(
            f,
            2,
            2,
            pure,
            Some("lumi_concat"),
            NO_F,
            ObjObjPtr,
            true,
            Always,
        ),
        ListTake => bi(
            f,
            2,
            2,
            pure,
            Some("lumi_list_take"),
            NO_F,
            ObjI64Ptr,
            // Slice view retains parent at runtime; escape of the take result
            // (not every use) marks the source via propagate.
            false,
            Always,
        ),
        ListReverse => bi(
            f,
            1,
            1,
            pure,
            Some("lumi_list_reverse"),
            NO_F,
            UnaryObjPtr,
            true,
            Always,
        ),
        ListSort => bi(
            f,
            1,
            1,
            pure,
            Some("lumi_list_sort"),
            NO_F,
            UnaryObjPtr,
            true,
            Always,
        ),
        ListSortByKeys => bi(
            f,
            2,
            2,
            pure,
            Some("lumi_list_sort_by_keys"),
            NO_F,
            ObjObjPtr,
            true,
            Always,
        ),
        ListParMap => bi(
            f,
            2,
            2,
            pure,
            Some("lumi_list_par_map"),
            NO_F,
            Custom,
            true,
            Always,
        ),
        ListParFold => bi(
            f,
            3,
            3,
            pure,
            Some("lumi_list_par_fold"),
            NO_F,
            Custom,
            true,
            Typed,
        ),
        ListJoin => bi(
            f,
            2,
            2,
            pure,
            Some("lumi_list_join"),
            NO_F,
            ObjObjPtr,
            false,
            Always,
        ),
        Elems => bi(
            f,
            1,
            1,
            pure,
            Some("lumi_elems"),
            NO_F,
            UnaryObjPtr,
            true,
            Always,
        ),
        Range => bi(
            f,
            2,
            2,
            pure,
            Some("lumi_range"),
            NO_F,
            I64I64Ptr,
            true,
            Always,
        ),
        RangeInclusive => bi(
            f,
            2,
            2,
            pure,
            Some("lumi_range_inclusive"),
            NO_F,
            I64I64Ptr,
            true,
            Always,
        ),
        _ => unreachable!("info_list: {b:?}"),
    }
}
