#!/usr/bin/env bash
# Install `lumi` for NixOS:
#   ~/.local/lib/lumi/lumi      — full compiler (LLVM)
#   ~/.local/lib/lumi/lumi-lsp  — slim LSP (no LLVM; fast cold start)
#   ~/.local/bin/lumi           — wrapper with baked library paths
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck source=env.sh
source "$ROOT/scripts/env.sh"

PROFILE="${1:-release}"
case "$PROFILE" in
  release)
    CARGO_FLAGS=(--release)
    OUT_DIR=release
    ;;
  dev|debug)
    CARGO_FLAGS=()
    OUT_DIR=debug
    ;;
  *)
    echo "usage: $0 [release|debug]" >&2
    exit 1
    ;;
esac

echo "== build slim lumi-lsp (no codegen / LLVM) =="
cargo build -p lumi --no-default-features "${CARGO_FLAGS[@]}" --manifest-path "$ROOT/Cargo.toml"
LSP_SRC="$ROOT/target/$OUT_DIR/lumi"
if [[ ! -x "$LSP_SRC" ]]; then
  echo "missing $LSP_SRC" >&2
  exit 1
fi
# Preserve slim binary before the full rebuild overwrites target/*/lumi.
cp -f "$LSP_SRC" /tmp/lumi-lsp-build.$$
trap 'rm -f /tmp/lumi-lsp-build.$$' EXIT

echo "== build full lumi (codegen) =="
cargo build -p lumi "${CARGO_FLAGS[@]}" --manifest-path "$ROOT/Cargo.toml"
BIN_SRC="$ROOT/target/$OUT_DIR/lumi"
if [[ ! -x "$BIN_SRC" ]]; then
  echo "missing $BIN_SRC" >&2
  exit 1
fi

LIBEXEC="${HOME}/.local/lib/lumi"
BIN_WRAP="${HOME}/.local/bin/lumi"
mkdir -p "$LIBEXEC" "$(dirname "$BIN_WRAP")"
cp -f "$BIN_SRC" "$LIBEXEC/lumi"
cp -f /tmp/lumi-lsp-build.$$ "$LIBEXEC/lumi-lsp"
chmod +x "$LIBEXEC/lumi" "$LIBEXEC/lumi-lsp"

# Resolve shared-lib dirs once at install time (avoid /nix/store globs on every launch).
_LIB_DIRS=()
_add_lib() {
  local p="$1"
  if [[ -d "$p" && "$p" != *"-static"* && "$p" != *static/lib ]]; then
    _LIB_DIRS+=("$p")
  fi
}
shopt -s nullglob
for p in \
  /nix/store/*-llvm-21.1.8-lib/lib \
  /nix/store/*-libffi-*/lib \
  /nix/store/*-zlib-*/lib \
  /nix/store/*-libxml2-*/lib \
  /nix/store/*-gcc-*-lib/lib; do
  _add_lib "$p"
done
LLVM_PREFIX=""
for p in /nix/store/*-llvm-21.1.8-dev; do
  if [[ -x "$p/bin/llvm-config" ]]; then
    LLVM_PREFIX="$p"
    break
  fi
done
shopt -u nullglob

JOINED=$(IFS=:; echo "${_LIB_DIRS[*]}")
LIBEXEC_ABS="$(cd "$LIBEXEC" && pwd)"

{
  echo '#!/usr/bin/env bash'
  echo '# Generated by scripts/install.sh — library paths baked at install time.'
  echo "export LD_LIBRARY_PATH=\"${JOINED}\${LD_LIBRARY_PATH:+:}\$LD_LIBRARY_PATH\""
  echo "export LIBRARY_PATH=\"${JOINED}\${LIBRARY_PATH:+:}\$LIBRARY_PATH\""
  if [[ -n "$LLVM_PREFIX" ]]; then
    echo "export LLVM_SYS_211_PREFIX=\"${LLVM_PREFIX}\""
  fi
  echo "LIBEXEC=\"${LIBEXEC_ABS}\""
  cat << 'WRAP'
if [[ "${1:-}" == "lsp" ]]; then
  exec "$LIBEXEC/lumi-lsp" "$@"
fi
exec "$LIBEXEC/lumi" "$@"
WRAP
} > "$BIN_WRAP"
chmod +x "$BIN_WRAP"

echo "installed: $BIN_WRAP"
echo "  compiler: $LIBEXEC/lumi ($(du -h "$LIBEXEC/lumi" | cut -f1))"
echo "  lsp:      $LIBEXEC/lumi-lsp ($(du -h "$LIBEXEC/lumi-lsp" | cut -f1))"
